import Head from 'next/head'

export default function Politica() {
    return (
        <>

            <Head>
                <title>Politica do Site</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <section>
                <div className="container py-5">
                    <div className="row">
                        <div className="col d-flex justify-content-center">
                            <h1 align="center">Política do Site XBZ Brindes</h1>
                        </div>
                    </div>
                    <div className="row">
                        <h5 className="ps-5 pt-5">
                            Só atendemos empresas de brindes promocionais.<br />
                            Não atendemos à clientes finais e outros tipos de revenda.<br />
                            Cotação somente para clientes cadastrados.
                        </h5>
                    </div>
                </div>
            </section>














            <section>
                <div className="container">
                    <div className="row pb-3">
                        <div className="col d-flex ">
                            <h5>Política de Entrega</h5>
                        </div>
                    </div>

                    <div className="row">
                        <div className="col-12">
                            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem rerum totam sapiente reprehenderit adipisci aliquid magnam recusandae voluptatum illum quae ut praesentium magni distinctio facere blanditiis atque, exercitationem ratione minus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem rerum totam sapiente reprehenderit adipisci aliquid magnam recusandae voluptatum illum quae ut praesentium magni distinctio facere blanditiis atque, exercitationem ratione minus!</p>

                            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem rerum totam sapiente reprehenderit adipisci aliquid magnam recusandae voluptatum illum quae ut praesentium magni</p>

                            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem rerum totam sapiente reprehenderit adipisci aliquid magnam recusandae voluptatum illum quae ut praesentium magni distinctio facere </p>

                            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem rerum totam sapiente reprehenderit adipisci</p>

                            <div className="table-responsive d-none d-md-block">
                                <table className="table">
                                    <thead>
                                        <tr className="bg-light">
                                            <th>Transportadora</th>
                                            <th>PADRÃO<br />5 - 7 dias úteis **</th>
                                            <th>PRIORIDADE<br />2 - 3 dias úteis **</th>
                                            <th>DIA SEGUINTE<br />Próximo dia útil **</th>
                                        </tr>
                                    </thead>

                                    <tbody>
                                        <tr>
                                            <td>Transportadora 1</td>
                                            <td>R$160,00</td>
                                            <td>R$160,00</td>
                                            <td>R$160,00</td>
                                        </tr>
                                        <tr>
                                            <td>Transportadora 2</td>
                                            <td>R$210,00</td>
                                            <td>R$160,00</td>
                                            <td>R$160,00</td>
                                        </tr>
                                        <tr>
                                            <td>Transportadora 3</td>
                                            <td>R$290,00</td>
                                            <td>R$160,00</td>
                                            <td>R$160,00</td>
                                        </tr>
                                        <tr>
                                            <td>Transportadora 4</td>
                                            <td>R$340,00</td>
                                            <td>R$160,00</td>
                                            <td>R$160,00</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>

                            <p className="m-0">* Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
                            <p>** Lorem ipsum dolor sit amet consectetur adipisicing elit amet consectetur adipisicing elit.</p>
                        </div>
                    </div>
                </div>
            </section>

            <section>
                <div className="container py-4 py-md-5">
                    <div className="row">
                        <div className="col">
                            <h5>Garantia de Produto</h5>
                            <p>1 - Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci beatae praesentium quasi illum ad recusandae perspiciatis temporibus autem voluptatum delectus quos repellendus</p>
                            <p>2 - Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci beatae praesentium quasi illum ad recusandae perspiciatis temporibus autem voluptatum delectus quos repellendusLorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci beatae praesentium quasi illum ad recusandae perspiciatis temporibus autem voluptatum delectus quos repellendusLorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci beatae praesentium quasi illum ad recusandae perspiciatis temporibus autem voluptatum delectus quos repellendusLorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci beatae praesentium quasi illum ad recusandae perspiciatis temporibus autem voluptatum delectus quos repellendusLorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci beatae praesentium quasi illum ad recusandae perspiciatis temporibus autem voluptatum delectus quos repellendus</p>
                            <p>3 - Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci beatae praesentium quasi illum ad recusandae perspiciatis temporibus autem voluptatum delectus quos repellendus</p>
                            <p>4 - Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci beatae praesentium quasi illum ad recusandae perspiciatis temporibus autem voluptatum delectus quos repellendusLorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci beatae praesentium quasi illum ad recusandae perspiciatis temporibus autem voluptatum delectus quos repellendus</p>
                            <p>5 - Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci beatae praesentium quasi illum ad recusandae perspiciatis temporibus autem voluptatum delectus quos repellendus</p>
                            <p>6 - Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci beatae praesentium quasi illum ad recusandae perspiciatis temporibus autem voluptatum delectus quos repellendusLorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci beatae praesentium quasi illum ad recusandae perspiciatis temporibus autem voluptatum delectus quos repellendus</p>
                            <p>7 - Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci beatae praesentium quasi illum ad recusandae perspiciatis temporibus autem voluptatum delectus quos repellendusLorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci beatae praesentium quasi illum ad recusandae perspiciatis temporibus autem voluptatum delectus quos repellendus</p>
                            <p>8 - Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci beatae praesentium quasi illum ad recusandae perspiciatis temporibus autem voluptatum delectus quos repellendus</p>
                            <p>9 - Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci beatae praesentium quasi illum ad recusandae perspiciatis temporibus autem voluptatum delectus quos repellendus</p>
                            <p>10 - Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci beatae praesentium quasi illum ad recusandae perspiciatis temporibus autem voluptatum delectus quos repellendus</p>
                            <p>11 - Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci beatae praesentium quasi illum ad recusandae perspiciatis temporibus autem voluptatum delectus quos repellendusLorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci beatae praesentium quasi illum ad recusandae perspiciatis temporibus autem voluptatum delectus quos repellendus</p>
                            <p>12 - Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci beatae praesentium quasi illum ad recusandae perspiciatis temporibus autem voluptatum delectus quos repellendus</p>
                            <p>13 - Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci beatae praesentium quasi illum ad recusandae perspiciatis temporibus autem voluptatum delectus quos repellendusLorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci beatae praesentium quasi illum ad recusandae perspiciatis temporibus autem voluptatum delectus quos repellendus</p>
                            <p>14 - Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci beatae praesentium quasi illum ad recusandae perspiciatis temporibus autem voluptatum delectus quos repellendusLorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci beatae praesentium quasi illum ad recusandae perspiciatis temporibus autem voluptatum delectus quos repellendus</p>
                            <p>15 - Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci beatae praesentium quasi illum ad recusandae perspiciatis temporibus autem voluptatum delectus quos repellendusLorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci beatae praesentium quasi illum ad recusandae perspiciatis temporibus autem voluptatum delectus quos repellendus</p>

                        </div>
                    </div>
                </div>
            </section>

            <section>
                <div className="container">
                    <div className="row">
                        <div className="col-md-8 py-4 py-md-0">
                            <h5>PROCEDIMENTO DE DEVOLUÇÃO</h5>

                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officia, ipsam eos! Odit assumenda ipsam fugiat est minus officiis molestias sunt, praesentium quae, ipsa magnam nemo suscipit atque hic debitis tempora.</p>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officia, ipsam eos! Odit assumenda ipsam fugiat est minus officiis molestias sunt, praesentium quae, ipsa magnam nemo suscipit atque hic debitis tempora.</p>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officia, ipsam eos! Odit assumenda ipsam fugiat est minus officiis molestias sunt, praesentium quae, ipsa magnam nemo suscipit atque hic debitis tempora.</p>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officia, ipsam eos! Odit assumenda ipsam fugiat est minus officiis molestias sunt, praesentium quae, ipsa magnam nemo suscipit atque hic debitis tempora.</p>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officia, ipsam eos! Odit assumenda ipsam fugiat est minus officiis molestias sunt, praesentium quae, ipsa magnam nemo suscipit atque hic debitis tempora.</p>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officia, ipsam eos! Odit assumenda ipsam fugiat est minus officiis molestias sunt, praesentium quae, ipsa magnam nemo suscipit atque hic debitis tempora.</p>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officia, ipsam eos! Odit assumenda ipsam fugiat est minus officiis molestias sunt, praesentium quae, ipsa magnam nemo suscipit atque hic debitis tempora.</p>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officia, ipsam eos! Odit assumenda ipsam fugiat est minus officiis molestias sunt, praesentium quae, ipsa magnam nemo suscipit atque hic debitis tempora.</p>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officia, ipsam eos! Odit assumenda ipsam fugiat est minus officiis molestias sunt, praesentium quae, ipsa magnam nemo suscipit atque hic debitis tempora.</p>
                        </div>
                        <div className="col-md-4 order-first order-md-last">
                            <h5>Suporte Técnico</h5>

                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officia, ipsam eos! Odit assumenda ipsam fugiat est minus officiis molestias sunt, praesentium quae, ipsa magnam nemo suscipit atque hic debitis tempora.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officia, ipsam eos! Odit assumenda ipsam fugiat est minus officiis molestias sunt, praesentium quae, ipsa magnam nemo suscipit atque hic debitis tempora.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officia, ipsam eos! Odit assumenda ipsam fugiat est minus officiis molestias sunt, praesentium quae, ipsa magnam nemo suscipit atque hic debitis tempora.</p>
                        </div>
                    </div>
                </div>
            </section>
        </>
    )
}